# Everything in this section will be available as an environment variable
# .streamlit/secrets.toml
db_username = "apurvtyagi26"
db_password = "Jonty2020"
cluster_name = "cluster-blockchain-data.a0jvoed.mongodb.net"
db_name = "bitcoin_database"

# You can also add other sections if you like.
# The contents of sections as shown below will not become environment variables,
# but they'll be easily accessible from within Streamlit anyway as we show
# later in this doc.
# [my_cool_secrets]
# things_i_like = ["Streamlit", "Python"]